name: flutter_bookly_app
description: MVVM Bookly Flutter App.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_storage: ^2.1.1
  go_router: ^7.0.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
