name: flutter_bookly_app
description: MVVM Bookly Flutter App.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  #  provider: ^6.0.5
  #  sqflite: ^2.2.6
  http: ^0.13.5
  intl: ^0.17.0
  google_fonts: ^4.0.3
  modal_progress_hud_nsn: ^0.3.0
  font_awesome_flutter: ^10.4.0
  #  hive: ^2.2.3
  #  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.2
  go_router: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #  hive_generator: ^2.0.0
  #  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf